/// Maps FIPS ADM1 codes to state/province names.
///
/// Format: "{country_fips}{2-digit code}" e.g. "US06" → "California"
pub fn adm1_name(code: &str) -> Option<&'static str> {
    match code {
        // India
        "IN01" => Some("Andaman and Nicobar Islands"),
        "IN02" => Some("Andhra Pradesh"),
        "IN03" => Some("Assam"),
        "IN05" => Some("Chandigarh"),
        "IN06" => Some("Dadra and Nagar Haveli"),
        "IN07" => Some("Delhi"),
        "IN09" => Some("Gujarat"),
        "IN10" => Some("Haryana"),
        "IN11" => Some("Himachal Pradesh"),
        "IN12" => Some("Jammu and Kashmir"),
        "IN13" => Some("Kerala"),
        "IN14" => Some("Lakshadweep"),
        "IN15" => Some("Madhya Pradesh"),
        "IN16" => Some("Maharashtra"),
        "IN17" => Some("Manipur"),
        "IN18" => Some("Meghalaya"),
        "IN19" => Some("Karnataka"),
        "IN20" => Some("Nagaland"),
        "IN21" => Some("Odisha Orissa"),
        "IN22" => Some("Puducherry Pondicherry"),
        "IN23" => Some("Punjab"),
        "IN24" => Some("Rajasthan"),
        "IN25" => Some("Sikkim"),
        "IN26" => Some("Tamil Nadu"),
        "IN27" => Some("Tripura"),
        "IN28" => Some("Uttar Pradesh"),
        "IN29" => Some("West Bengal"),
        "IN30" => Some("Arunachal Pradesh"),
        "IN31" => Some("Mizoram"),
        "IN32" => Some("Daman and Diu"),
        "IN33" => Some("Goa"),
        "IN34" => Some("Chhattisgarh"),
        "IN35" => Some("Jharkhand"),
        "IN36" => Some("Uttarakhand Uttaranchal"),
        "IN37" => Some("Telangana"),
        "IN38" => Some("Ladakh"),
        "IN40" => Some("Bihar"),

        // United States
        "US01" => Some("Alabama"),
        "US02" => Some("Alaska"),
        "US04" => Some("Arizona"),
        "US05" => Some("Arkansas"),
        "US06" => Some("California"),
        "US08" => Some("Colorado"),
        "US09" => Some("Connecticut"),
        "US10" => Some("Delaware"),
        "US11" => Some("District of Columbia Washington DC"),
        "US12" => Some("Florida"),
        "US13" => Some("Georgia"),
        "US15" => Some("Hawaii"),
        "US16" => Some("Idaho"),
        "US17" => Some("Illinois"),
        "US18" => Some("Indiana"),
        "US19" => Some("Iowa"),
        "US20" => Some("Kansas"),
        "US21" => Some("Kentucky"),
        "US22" => Some("Louisiana"),
        "US23" => Some("Maine"),
        "US24" => Some("Maryland"),
        "US25" => Some("Massachusetts"),
        "US26" => Some("Michigan"),
        "US27" => Some("Minnesota"),
        "US28" => Some("Mississippi"),
        "US29" => Some("Missouri"),
        "US30" => Some("Montana"),
        "US31" => Some("Nebraska"),
        "US32" => Some("Nevada"),
        "US33" => Some("New Hampshire"),
        "US34" => Some("New Jersey"),
        "US35" => Some("New Mexico"),
        "US36" => Some("New York"),
        "US37" => Some("North Carolina"),
        "US38" => Some("North Dakota"),
        "US39" => Some("Ohio"),
        "US40" => Some("Oklahoma"),
        "US41" => Some("Oregon"),
        "US42" => Some("Pennsylvania"),
        "US44" => Some("Rhode Island"),
        "US45" => Some("South Carolina"),
        "US46" => Some("South Dakota"),
        "US47" => Some("Tennessee"),
        "US48" => Some("Texas"),
        "US49" => Some("Utah"),
        "US50" => Some("Vermont"),
        "US51" => Some("Virginia"),
        "US53" => Some("Washington"),
        "US54" => Some("West Virginia"),
        "US55" => Some("Wisconsin"),
        "US56" => Some("Wyoming"),

        // United Kingdom
        "UK01" => Some("England Barking and Dagenham"),
        "UK05" => Some("England Bedfordshire"),
        "UK07" => Some("England Berkshire"),
        "UK09" => Some("England Buckinghamshire"),
        "UK10" => Some("England Cambridgeshire"),
        "UK13" => Some("England Cheshire"),
        "UK16" => Some("England Cornwall"),
        "UK18" => Some("England Cumbria"),
        "UK19" => Some("England Derbyshire"),
        "UK20" => Some("England Devon"),
        "UK21" => Some("England Dorset"),
        "UK23" => Some("England Durham"),
        "UK24" => Some("England East Sussex"),
        "UK26" => Some("England Essex"),
        "UK29" => Some("England Gloucestershire"),
        "UK30" => Some("England Greater London"),
        "UK31" => Some("England Greater Manchester"),
        "UK33" => Some("England Hampshire"),
        "UK36" => Some("England Hereford and Worcester"),
        "UK37" => Some("England Hertfordshire"),
        "UK40" => Some("England Isle of Wight"),
        "UK41" => Some("England Kent"),
        "UK42" => Some("England Lancashire"),
        "UK44" => Some("England Leicestershire"),
        "UK45" => Some("England Lincolnshire"),
        "UK47" => Some("England Merseyside"),
        "UK48" => Some("England Norfolk"),
        "UK50" => Some("England Northamptonshire"),
        "UK51" => Some("England Northumberland"),
        "UK52" => Some("England North Yorkshire"),
        "UK53" => Some("England Nottinghamshire"),
        "UK54" => Some("England Oxfordshire"),
        "UK56" => Some("England Shropshire"),
        "UK57" => Some("England Somerset"),
        "UK58" => Some("England South Yorkshire"),
        "UK59" => Some("England Staffordshire"),
        "UK60" => Some("England Suffolk"),
        "UK61" => Some("England Surrey"),
        "UK63" => Some("England Tyne and Wear"),
        "UK64" => Some("England Warwickshire"),
        "UK65" => Some("England West Midlands"),
        "UK66" => Some("England West Sussex"),
        "UK67" => Some("England West Yorkshire"),
        "UK68" => Some("England Wiltshire"),
        "UK72" => Some("Scotland Borders"),
        "UK73" => Some("Scotland Central"),
        "UK75" => Some("Scotland Dumfries and Galloway"),
        "UK77" => Some("Scotland Fife"),
        "UK78" => Some("Scotland Grampian"),
        "UK79" => Some("Scotland Highland"),
        "UK80" => Some("Scotland Lothian Edinburgh"),
        "UK83" => Some("Scotland Strathclyde Glasgow"),
        "UK84" => Some("Scotland Tayside"),
        "UK86" => Some("Scotland Orkney Islands"),
        "UK87" => Some("Scotland Shetland Islands"),
        "UK88" => Some("Scotland Western Isles"),
        "UK91" => Some("Wales Clwyd"),
        "UK92" => Some("Wales Dyfed"),
        "UK93" => Some("Wales Gwent"),
        "UK94" => Some("Wales Gwynedd"),
        "UK95" => Some("Wales Mid Glamorgan"),
        "UK96" => Some("Wales Powys"),
        "UK97" => Some("Wales South Glamorgan Cardiff"),
        "UK98" => Some("Wales West Glamorgan Swansea"),
        "UK99" => Some("Northern Ireland"),

        // China
        "CH01" => Some("Anhui"),
        "CH02" => Some("Zhejiang"),
        "CH03" => Some("Jiangxi"),
        "CH04" => Some("Jiangsu"),
        "CH05" => Some("Jilin"),
        "CH06" => Some("Qinghai"),
        "CH07" => Some("Fujian"),
        "CH08" => Some("Heilongjiang"),
        "CH09" => Some("Henan"),
        "CH10" => Some("Hebei"),
        "CH11" => Some("Hunan"),
        "CH12" => Some("Hubei"),
        "CH13" => Some("Xinjiang Uighur"),
        "CH14" => Some("Tibet Xizang"),
        "CH15" => Some("Gansu"),
        "CH16" => Some("Guangxi"),
        "CH18" => Some("Guizhou"),
        "CH19" => Some("Liaoning"),
        "CH20" => Some("Inner Mongolia Nei Mongol"),
        "CH21" => Some("Ningxia"),
        "CH22" => Some("Beijing"),
        "CH23" => Some("Shanghai"),
        "CH24" => Some("Shanxi"),
        "CH25" => Some("Shandong"),
        "CH26" => Some("Shaanxi"),
        "CH28" => Some("Tianjin"),
        "CH29" => Some("Yunnan"),
        "CH30" => Some("Guangdong"),
        "CH31" => Some("Hainan"),
        "CH32" => Some("Sichuan"),
        "CH33" => Some("Chongqing"),

        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_us06_california() {
        assert_eq!(adm1_name("US06"), Some("California"));
    }

    #[test]
    fn test_us36_new_york() {
        assert_eq!(adm1_name("US36"), Some("New York"));
    }

    #[test]
    fn test_in26_tamil_nadu() {
        assert_eq!(adm1_name("IN26"), Some("Tamil Nadu"));
    }

    #[test]
    fn test_unknown_code() {
        assert_eq!(adm1_name("ZZ99"), None);
    }
}
