/// Maps FIPS 10-4 country codes (used by GDELT) to country names.
pub fn country_name(fips_code: &str) -> Option<&'static str> {
    match fips_code {
        "AF" => Some("Afghanistan"),
        "AX" => Some("Akrotiri"),
        "AL" => Some("Albania"),
        "AG" => Some("Algeria"),
        "AQ" => Some("American Samoa"),
        "AN" => Some("Andorra"),
        "AO" => Some("Angola"),
        "AV" => Some("Anguilla"),
        "AY" => Some("Antarctica"),
        "AC" => Some("Antigua and Barbuda"),
        "AR" => Some("Argentina"),
        "AM" => Some("Armenia"),
        "AA" => Some("Aruba"),
        "AS" => Some("Australia"),
        "AU" => Some("Austria"),
        "AJ" => Some("Azerbaijan"),
        "BF" => Some("Bahamas"),
        "BA" => Some("Bahrain"),
        "BG" => Some("Bangladesh"),
        "BB" => Some("Barbados"),
        "BO" => Some("Belarus"),
        "BE" => Some("Belgium"),
        "BH" => Some("Belize"),
        "BN" => Some("Benin"),
        "BD" => Some("Bermuda"),
        "BT" => Some("Bhutan"),
        "BL" => Some("Bolivia"),
        "BK" => Some("Bosnia and Herzegovina"),
        "BC" => Some("Botswana"),
        "BR" => Some("Brazil"),
        "IO" => Some("British Indian Ocean Territory"),
        "VI" => Some("British Virgin Islands"),
        "BX" => Some("Brunei"),
        "BU" => Some("Bulgaria"),
        "UV" => Some("Burkina Faso"),
        "BM" => Some("Burma Myanmar"),
        "BY" => Some("Burundi"),
        "CV" => Some("Cabo Verde"),
        "CB" => Some("Cambodia"),
        "CM" => Some("Cameroon"),
        "CA" => Some("Canada"),
        "CJ" => Some("Cayman Islands"),
        "CT" => Some("Central African Republic"),
        "CD" => Some("Chad"),
        "CI" => Some("Chile"),
        "CH" => Some("China"),
        "KT" => Some("Christmas Island"),
        "CK" => Some("Cocos Keeling Islands"),
        "CO" => Some("Colombia"),
        "CN" => Some("Comoros"),
        "CG" => Some("Congo Brazzaville"),
        "CF" => Some("Congo Kinshasa Democratic Republic"),
        "CW" => Some("Cook Islands"),
        "CS" => Some("Costa Rica"),
        "IV" => Some("Cote d'Ivoire Ivory Coast"),
        "HR" => Some("Croatia"),
        "CU" => Some("Cuba"),
        "UC" => Some("Curacao"),
        "CY" => Some("Cyprus"),
        "EZ" => Some("Czech Republic Czechia"),
        "DA" => Some("Denmark"),
        "DJ" => Some("Djibouti"),
        "DO" => Some("Dominica"),
        "DR" => Some("Dominican Republic"),
        "EC" => Some("Ecuador"),
        "EG" => Some("Egypt"),
        "ES" => Some("El Salvador"),
        "EK" => Some("Equatorial Guinea"),
        "ER" => Some("Eritrea"),
        "EN" => Some("Estonia"),
        "WZ" => Some("Eswatini Swaziland"),
        "ET" => Some("Ethiopia"),
        "FK" => Some("Falkland Islands"),
        "FO" => Some("Faroe Islands"),
        "FJ" => Some("Fiji"),
        "FI" => Some("Finland"),
        "FR" => Some("France"),
        "FP" => Some("French Polynesia"),
        "FS" => Some("French Southern Territories"),
        "GB" => Some("Gabon"),
        "GA" => Some("Gambia"),
        "GG" => Some("Georgia"),
        "GM" => Some("Germany"),
        "GH" => Some("Ghana"),
        "GI" => Some("Gibraltar"),
        "GR" => Some("Greece"),
        "GL" => Some("Greenland"),
        "GJ" => Some("Grenada"),
        "GQ" => Some("Guam"),
        "GT" => Some("Guatemala"),
        "GK" => Some("Guernsey"),
        "GV" => Some("Guinea"),
        "PU" => Some("Guinea-Bissau"),
        "GY" => Some("Guyana"),
        "HA" => Some("Haiti"),
        "HO" => Some("Honduras"),
        "HK" => Some("Hong Kong"),
        "HU" => Some("Hungary"),
        "IC" => Some("Iceland"),
        "IN" => Some("India"),
        "ID" => Some("Indonesia"),
        "IR" => Some("Iran"),
        "IZ" => Some("Iraq"),
        "EI" => Some("Ireland"),
        "IM" => Some("Isle of Man"),
        "IS" => Some("Israel"),
        "IT" => Some("Italy"),
        "JM" => Some("Jamaica"),
        "JA" => Some("Japan"),
        "JE" => Some("Jersey"),
        "JO" => Some("Jordan"),
        "KZ" => Some("Kazakhstan"),
        "KE" => Some("Kenya"),
        "KR" => Some("Kiribati"),
        "KN" => Some("North Korea"),
        "KS" => Some("South Korea"),
        "KU" => Some("Kuwait"),
        "KG" => Some("Kyrgyzstan"),
        "LA" => Some("Laos"),
        "LG" => Some("Latvia"),
        "LE" => Some("Lebanon"),
        "LT" => Some("Lesotho"),
        "LI" => Some("Liberia"),
        "LY" => Some("Libya"),
        "LS" => Some("Liechtenstein"),
        "LH" => Some("Lithuania"),
        "LU" => Some("Luxembourg"),
        "MC" => Some("Macau"),
        "MK" => Some("North Macedonia"),
        "MA" => Some("Madagascar"),
        "MI" => Some("Malawi"),
        "MY" => Some("Malaysia"),
        "MV" => Some("Maldives"),
        "ML" => Some("Mali"),
        "MT" => Some("Malta"),
        "RM" => Some("Marshall Islands"),
        "MR" => Some("Mauritania"),
        "MP" => Some("Mauritius"),
        "MF" => Some("Mayotte"),
        "MX" => Some("Mexico"),
        "FM" => Some("Micronesia"),
        "MD" => Some("Moldova"),
        "MN" => Some("Monaco"),
        "MG" => Some("Mongolia"),
        "MJ" => Some("Montenegro"),
        "MH" => Some("Montserrat"),
        "MO" => Some("Morocco"),
        "MZ" => Some("Mozambique"),
        "WA" => Some("Namibia"),
        "NR" => Some("Nauru"),
        "NP" => Some("Nepal"),
        "NL" => Some("Netherlands"),
        "NC" => Some("New Caledonia"),
        "NZ" => Some("New Zealand"),
        "NU" => Some("Nicaragua"),
        "NG" => Some("Niger"),
        "NI" => Some("Nigeria"),
        "NE" => Some("Niue"),
        "NF" => Some("Norfolk Island"),
        "CQ" => Some("Northern Mariana Islands"),
        "NO" => Some("Norway"),
        "MU" => Some("Oman"),
        "PK" => Some("Pakistan"),
        "PS" => Some("Palau"),
        "PP" => Some("Papua New Guinea"),
        "PM" => Some("Panama"),
        "PA" => Some("Panama"),
        "PE" => Some("Peru"),
        "RP" => Some("Philippines"),
        "PC" => Some("Pitcairn Islands"),
        "PL" => Some("Poland"),
        "PO" => Some("Portugal"),
        "RQ" => Some("Puerto Rico"),
        "QA" => Some("Qatar"),
        "RO" => Some("Romania"),
        "RS" => Some("Russia"),
        "RW" => Some("Rwanda"),
        "SC" => Some("Saint Kitts and Nevis"),
        "ST" => Some("Saint Lucia"),
        "VC" => Some("Saint Vincent and the Grenadines"),
        "WS" => Some("Samoa"),
        "SM" => Some("San Marino"),
        "TP" => Some("Sao Tome and Principe"),
        "SA" => Some("Saudi Arabia"),
        "SG" => Some("Senegal"),
        "RI" => Some("Serbia"),
        "SE" => Some("Seychelles"),
        "SL" => Some("Sierra Leone"),
        "SN" => Some("Singapore"),
        "SK" => Some("Sint Maarten"),
        "LO" => Some("Slovakia"),
        "SI" => Some("Slovenia"),
        "BP" => Some("Solomon Islands"),
        "SO" => Some("Somalia"),
        "SF" => Some("South Africa"),
        "OD" => Some("South Sudan"),
        "SP" => Some("Spain"),
        "CE" => Some("Sri Lanka"),
        "SU" => Some("Sudan"),
        "NS" => Some("Suriname"),
        "SW" => Some("Sweden"),
        "SZ" => Some("Switzerland"),
        "SY" => Some("Syria"),
        "TW" => Some("Taiwan"),
        "TI" => Some("Tajikistan"),
        "TZ" => Some("Tanzania"),
        "TH" => Some("Thailand"),
        "TT" => Some("Timor-Leste East Timor"),
        "TO" => Some("Togo"),
        "TL" => Some("Tokelau"),
        "TN" => Some("Tonga"),
        "TD" => Some("Trinidad and Tobago"),
        "TS" => Some("Tunisia"),
        "TU" => Some("Turkey Turkiye"),
        "TX" => Some("Turkmenistan"),
        "TK" => Some("Turks and Caicos Islands"),
        "TV" => Some("Tuvalu"),
        "UG" => Some("Uganda"),
        "UP" => Some("Ukraine"),
        "AE" => Some("United Arab Emirates UAE"),
        "UK" => Some("United Kingdom Great Britain England Scotland Wales Northern Ireland"),
        "US" => Some("United States America USA"),
        "UY" => Some("Uruguay"),
        "UZ" => Some("Uzbekistan"),
        "NH" => Some("Vanuatu"),
        "VT" => Some("Vatican City Holy See"),
        "VE" => Some("Venezuela"),
        "VM" => Some("Vietnam"),
        "VQ" => Some("Virgin Islands"),
        "WE" => Some("West Bank"),
        "GZ" => Some("Gaza Strip"),
        "WI" => Some("Western Sahara"),
        "YM" => Some("Yemen"),
        "ZA" => Some("Zambia"),
        "ZI" => Some("Zimbabwe"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_us_code() {
        assert_eq!(country_name("US"), Some("United States America USA"));
    }

    #[test]
    fn test_uk_code() {
        let result = country_name("UK");
        assert!(result.is_some());
        assert!(result.unwrap().contains("United Kingdom"));
    }

    #[test]
    fn test_unknown_code() {
        assert_eq!(country_name("XX"), None);
    }
}
